services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ecommerce\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations,Tests}'

    Ecommerce\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']