frontend_news_from_vendor:
  resource: "@NewsBundle/Resources/config/routes/frontend/all.yaml"
  prefix:   /

frontend_contact_from_vendor:
  resource: "@ContactBundle/Resources/config/routes/frontend/contact.yaml"
  prefix:   /contact

frontend_Static:
  resource: "@StaticBundle/Resources/config/routes/frontend/all.yaml"
  prefix:   /

frontend_homepage:
  path:     /
  methods: [GET]
  controller: FrontendBundle\Controller\HomepageController::indexAction

frontend_ajax_distribution:
  path:     /ajax/distribution
  controller: FrontendBundle\Controller\DefaultController::distributionAction
  requirements:
    slug: "[\\w-]+"
