frontend_product_photoswipe:
  path:  /photoswipe
  controller: Ecommerce\Controller\Frontend\ProductController::photoswipeAction
  
frontend_product_show:
  path:  /{slug}
  controller: Ecommerce\Controller\Frontend\ProductController::showProductAction
  requirements:
    _locale: '%app_locales%'
    slug: ".+"
