frontend_product_photoswipe:
  path:  /photoswipe
  controller: Ecommerce\Controller\Frontend\ProductController::photoswipeAction

frontend_ajax_category_products:
  path:     /ajax/{slug}
  controller: Ecommerce\Controller\Frontend\ProductController::getProductsByCategoryAction
  requirements:
    slug: "[\\w-]+"

frontend_ajax_application_field_products:
  path:     /application-field/ajax/{slug}
  controller: Ecommerce\Controller\Frontend\ProductController::getProductsByApplicationFieldAction
  requirements:
    slug: "[\\w-]+"
  
frontend_product_show:
  path:  /{slug}
  controller: Ecommerce\Controller\Frontend\ProductController::showProductAction
  requirements:
    _locale: '%app_locales%'
    slug: ".+"
