frontend_product_photoswipe:
  path:  /photoswipe
  controller: Ecommerce\Controller\Frontend\ProductController::photoswipeAction
  
frontend_product_show:
  path:  /{slug}
  controller: Ecommerce\Controller\Frontend\ProductController::showProductAction
  requirements:
    _locale: '%app_locales%'
    slug: ".+"

frontend_ajax_category_products:
  path:     /ajax/{slug}
  controller: Ecommerce\Controller\Frontend\ProductController::getProductsByCategoryAction
  requirements:
    slug: "[\\w-]+"
