frontend_product:
  resource: "@EcommerceBundle/Resources/config/frontend/product.yaml"
  prefix: /product

frontend_product_category:
  resource: "@EcommerceBundle/Resources/config/frontend/product_category.yaml"
  prefix: /category

frontend_activity_area:
  resource: "@EcommerceBundle/Resources/config/frontend/activity_area.yaml"
  prefix: /activity-area

frontend_project:
  resource: "@EcommerceBundle/Resources/config/frontend/project.yaml"
  prefix: /project

application_field:
  resource: "@EcommerceBundle/Resources/config/frontend/application_field.yaml"
  prefix: /application-field