frontend_search_shop_from_header_save:
  path:     /from-header/save/
  controller: Ecommerce\Controller\Frontend\SearchShopController::searchShopSaveAction
  methods:  POST

frontend_search_shop_index:
    path:     /{page}/{countInPage}/{searchStr}
    controller: Ecommerce\Controller\SearchShopController::getSearchResultsAction
    defaults:
        page: 1
        countInPage: 9
        searchStr: null
    requirements:
        page:  \d+
        countInPage:  \d+
